### ISSUE TITLE
Womit?

### ISSUE THREAD

**Issue by meaku** [web-and-wine/www#1]
Grad zufällig auf der jsunconf website entdeckt: http://wintersmith.io

**Comment by Fannon** [comment]
Gibt's ne Menge davon. Wintersmith wollte ich mir auch mal ansehen, bin aber leider nicht wirklich dazugekommen. Hier ist eine gute Übersicht, sortierbar nach JavaScript (wäre ja irgendwie sinnvoll ;) ) und GitHub Sternen: https://www.staticgen.com/

**Comment by meaku** [comment]
Merci!

**Comment by flootr** [comment]
seems to work http://webandwine.org/ (related to dns entries and so on)
