### ISSUE TITLE
Ort Augsburg klarer rausstellen

### ISSUE THREAD

**Issue by meaku** [web-and-wine/www#3]
Ich hab den anderen peerigonen die website gezeigt und sie hat getaugt! Nur ein Verbessungsvorschlag kam... -> "Es wird nicht schnell klar dass es in Augsburg statt findet". 

Sollen wir's klarer formulieren?

**Comment by MartinKolb1987** [comment]
Absolut. Haben wir irgendwie verschlafen :-D . Hab es aktualisiert!

**Comment by meaku** [comment]
Danke :)
