### ISSUE TITLE
Umziehen nach web-and-wine.github.io

### ISSUE THREAD

**Issue by meaku** [web-and-wine/www#4]
Ein repo namens _organame_.github.io ist der empfohlene Weg für Organization Sites. Ich find allerdings ein www Repo irgendwie sprechender. Nachdem is das Orga Repo gelöscht hatte, ging allerdings www nicht mehr. Mehr dazu siehe hier: http://stackoverflow.com/questions/23554086/creating-a-github-project-page-for-a-repository-owned-by-an-organization

Also entweder ein leeres Repo behalten oder umziehen. Eigentlich isses ja egal da man von außen eh über die Domain drauf geht.

**Comment by zalvus** [comment]
Okay. Fand die www Variante auch sprechender. Aber web-andwine.gihtub.io passt auch. Man muss es halt wissen. Danke fürs Abchecken.

**Comment by MartinKolb1987** [comment]
Okay. Fand die www Variante auch sprechender. Aber web-andwine.gihtub.io passt auch. Man muss es halt wissen. Danke fürs Abchecken.

**Comment by Fannon** [comment]
Ich glaub nicht, dass jemand auf GitHub nach der Webseite sucht ;)
Solange wir uns auskennen passt ja alles.
